theme: jekyll-theme-minimal
title: "## <Henni Veikkonen> Web-tehtävä"
description: "Lopputyö OK"

# Subtle fall colors
sass:
  custom_css: /assets/css/style.css                                           
