theme: jekyll-theme-minimal
title: "Lopputyö OK"
description: "## <Henni Veikkonen> Web-tehtävä"

# Subtle fall colors
sass:
  custom_css: /assets/css/style.css                                           
